#spring:
#  profiles:
#    active: product
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/financialdata?characterEncoding=utf-8
#    username: root
#    password: 12345678
#  thymeleaf:
#    prefix: classpath:/dist/