#spring:
#  profiles:
#    active: product
#  datasource:
#    url: jdbc:mysql://localhost:3306/financialdata?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: 12345678
#  thymeleaf:
#    prefix: classpath:/dist/